INSERT INTO risques (nature)
VALUES ('accident de plain-pied'),
('activité physique'),
('agents biologiques'),
('ambiances sonores'),
('ambiances thermiques'),
('autonomie dans le travail'),
('autres'),
('chute de hauteur'),
('circulations internes'),
('conflits de valeurs'),
('éclairage'),
('effondrements et chutes d’’objets'),
('électricité'),
('équipements de travail'),
('exigences de travail'),
('exigences émotionnelle'),
('incendie explosion'),
('manutention mécanique'),
('produits, émissions et déchets'),
('rapports sociaux'),
('rayonnements'),
('relations aux usagers'),
('routier')
;
