--Tableau

select 
    'table' as component,
    'Mineure' as markdown,
    'Significative' as markdown,
    'Grave' as markdown,
    'Critique' as markdown,
    'Mineure' as align_center,
    'Significative' as align_center,
    'Grave' as align_center,
    'Critique' as align_center,    
    TRUE as border,
    TRUE    as hover,
    TRUE    as striped_rows,
    TRUE    as small;
select 
    freq as Probabilité,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=1 and frequence=0.5 ORDER BY risque.score ASC) as Mineure,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=2 and frequence=0.5 ORDER BY risque.score ASC) as Significative,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=3 and frequence=0.5 ORDER BY risque.score ASC) as Grave,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=4 and frequence=0.5 ORDER BY risque.score ASC) as Critique
    FROM frequence JOIN risque on risque.frequence=frequence.vfreq WHERE vfreq=0.5 GROUP BY vfreq;
select 
    freq as Probabilité,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir") **'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=1 and frequence=1 ORDER BY risque.score ASC) as Mineure,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=2 and frequence=1 ORDER BY risque.score ASC) as Significative,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=3 and frequence=1 ORDER BY risque.score ASC) as Grave,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=4 and frequence=1 ORDER BY risque.score ASC) as Critique
    FROM frequence JOIN risque on risque.frequence=frequence.vfreq WHERE vfreq=1 GROUP BY vfreq;
select 
    freq as Probabilité,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=1 and frequence=2 ORDER BY risque.score ASC) as Mineure,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=2 and frequence=2 ORDER BY risque.score ASC) as Significative,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=3 and frequence=2 ORDER BY risque.score ASC) as Grave,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=4 and frequence=2 ORDER BY risque.score ASC) as Critique
    FROM frequence JOIN risque on risque.frequence=frequence.vfreq WHERE vfreq=2 GROUP BY vfreq;
select 
    freq as Probabilité,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=1 and frequence=3 ORDER BY risque.score ASC) as Mineure,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=2 and frequence=3 ORDER BY risque.score ASC) as Significative,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=3 and frequence=3 ORDER BY risque.score ASC) as Grave,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=4 and frequence=3 ORDER BY risque.score ASC) as Critique
    FROM frequence JOIN risque on risque.frequence=frequence.vfreq WHERE vfreq=3 GROUP BY vfreq;
select 
    freq as Probabilité,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=1 and frequence=4 ORDER BY risque.score ASC) as Mineure,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=2 and frequence=4 ORDER BY risque.score ASC) as Significative,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=3 and frequence=4 ORDER BY risque.score ASC) as Grave,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=4 and frequence=4 ORDER BY risque.score ASC) as Critique
    FROM frequence JOIN risque on risque.frequence=frequence.vfreq WHERE vfreq=4 GROUP BY vfreq;
select 
    freq as Probabilité,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=1 and frequence=5 ORDER BY risque.score ASC) as Mineure,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=2 and frequence=5 ORDER BY risque.score ASC) as Significative,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=3 and frequence=5 ORDER BY risque.score ASC) as Grave,
    (SELECT    group_concat('[![Voir](/icons/alert-square-'||risque.color||'.svg)](/risque_fiche.sql?id='||risque.id||' "'||risque.score||'/100")[![Voir](/icons/files.svg)](/risque_fiche.sql?id='||risque.id||' "Voir")**'||unite.lieu||'**'||CHAR(10) || CHAR(10)||risques.nature,  CHAR(10) || CHAR(10))  FROM unite LEFT JOIN risque on unite.id=risque.unite_id LEFT JOIN risques on risque.type_id=risques.id LEFT JOIN maitrise on risque.maitrise=maitrise.id WHERE gravite=4 and frequence=5 ORDER BY risque.score ASC) as Critique
    FROM frequence JOIN risque on risque.frequence=frequence.vfreq WHERE vfreq=5 GROUP BY vfreq; 
